default_language_version:
  python: python3  # or python3.12 if that's your venv

repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: '(^|/)tests?/'
        additional_dependencies:
          - pydantic>=2.0
          - pytest>=7.0
          - msgpack-types>=0.2
          - types-PyYAML>=6.0.12
        args: ["--strict"]

  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: .venv/bin/pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["-ra", "-q", "tests"]
