[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pocketscope"
version = "0.1.0"
description = "PocketScope — a handheld Pi-powered ATC-style scope for decoding and displaying ADS-B traffic"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
  { name = "PocketScope Team" }
]

dependencies = [
  "pydantic>=2.0",
  "numpy>=1.24",
  "msgpack>=1.0"
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0",
  "black>=23.0",
  "ruff>=0.1.0",
  "isort>=5.12.0",
  "mypy>=1.5",
  "pre-commit>=3.0"
]

[project.scripts]
pocketscope = "pocketscope.__main__:main"
pocketscope-maxrange = "pocketscope.tools.max_range_tracker:main"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_configs = true
warn_return_any = true
disallow_untyped_defs = true
